# Generated by Django 3.1 on 2020-10-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='doi',
            field=models.CharField(max_length=255),
        ),
    ]
